# Generated by Django 5.2.6 on 2025-09-17 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('D', 'Dairy'), ('F', 'Frozen'), ('R', 'Refrigerated'), ('M&S', 'Meat & Seafood'), ('P/DG', 'Pantry/Dry Goods'), ('H', 'Houshold Items'), ('P', 'Produce')], default='D', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(null=True, to='main_app.supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
